from sqlalchemy import create_engine, Column, String, Float, DateTime
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class RawMatch(Base):
    __tablename__ = 'raw_matches'

    # Match Info
    date = Column(DateTime, primary_key=True)
    team = Column(String, primary_key=True)
    season = Column(String)
    time = Column(String)
    comp = Column(String)
    round = Column(String)
    day = Column(String)
    venue = Column(String)
    result = Column(String)
    opponent = Column(String)
    formation = Column(String)
    opp_formation = Column(String)
    match_report = Column(String)


    # Defensive Actions
    ga = Column(Float)
    xga = Column(Float)
    tkls = Column(Float)
    tkls_won = Column(Float)
    tkls_def_3rd = Column(Float)
    tkls_mid_3rd = Column(Float)
    tkls_att_3rd = Column(Float)
    dri_tkl = Column(Float)
    dri_chall = Column(Float)
    tkl_pct = Column(Float)
    chall_lost = Column(Float)
    blocks = Column(Float)
    sh_blk = Column(Float)
    pass_blk = Column(Float)
    int = Column(Float)
    tkl_plus_int = Column(Float)
    clr = Column(Float)
    err = Column(Float)

    # Goal and Shot Creation
    sca = Column(Float)
    sca_live_pass = Column(Float)
    sca_dead_pass = Column(Float)
    sca_dri = Column(Float)
    sca_sh = Column(Float)
    sca_fls = Column(Float)
    sca_def_ac = Column(Float)
    gca = Column(Float)
    gca_live_pass = Column(Float)
    gca_dead_pass = Column(Float)
    gca_dri = Column(Float)
    gca_sh = Column(Float)
    gca_fls = Column(Float)
    gca_def_ac = Column(Float)

    # Goalkeeping
    sota = Column(Float)
    saves = Column(Float)
    save_pct = Column(Float)
    cs = Column(Float)
    psxg = Column(Float)
    psxg_diff = Column(Float)
    pk_att_ag = Column(Float)
    pk_conc = Column(Float)
    pk_sv_ag = Column(Float)
    pk_miss_ag = Column(Float)
    lau_cmp = Column(Float)
    lau_att = Column(Float)
    lau_cmp_pct = Column(Float)
    pass_att = Column(Float)
    throws_att = Column(Float)
    pass_launch_pct = Column(Float)
    pass_avg_len = Column(Float)
    gk_att = Column(Float)
    gk_launch_pct = Column(Float)
    gk_avg_len = Column(Float)
    crosses_faced = Column(Float)
    crosses_stp = Column(Float)
    crosses_stp_pct = Column(Float)
    def_actionout_box_gk = Column(Float)
    avg_dist_of_def_action_gk = Column(Float)

    # Misc
    yell = Column(Float)
    red = Column(Float)
    fouls = Column(Float)
    fouls_drawn = Column(Float)
    off = Column(Float)
    crosses = Column(Float)
    pk_won = Column(Float)
    pk_con = Column(Float)
    recov = Column(Float)
    aerial_won = Column(Float)
    aerial_lost = Column(Float)
    aerial_won_pct = Column(Float)

    # Passing
    tot_pass_cmp = Column(Float)
    tot_pass_att = Column(Float)
    tot_pass_cmp_pct = Column(Float)
    tot_pass_dist = Column(Float)
    prg_pass_dist = Column(Float)
    spass_cmp = Column(Float)
    spas_att = Column(Float)
    spas_cmp_pct = Column(Float)
    mpas_cmp = Column(Float)
    mpas_att = Column(Float)
    mpas_cmp_pct = Column(Float)
    lpas_cmp = Column(Float)
    lpas_att = Column(Float)
    lpas_cmp_pct = Column(Float)
    ast = Column(Float)
    xag = Column(Float)
    xa = Column(Float)
    keypasses = Column(Float)
    pass_into_final_3rd = Column(Float)
    pass_into_box = Column(Float)
    crs_into_box = Column(Float)
    prg_pass = Column(Float)

    # Pass Types
    live_pass = Column(Float)
    dead_pass = Column(Float)
    passes_fk = Column(Float)
    through = Column(Float)
    switch = Column(Float)
    cross = Column(Float)
    throw_ins = Column(Float)
    ck = Column(Float)
    ck_in = Column(Float)
    ck_out = Column(Float)
    ck_straight = Column(Float)
    off_passes = Column(Float)
    blocked_passes = Column(Float)

    # Possesion
    poss = Column(Float)
    touches = Column(Float)
    def_box_touches = Column(Float)
    def_3rd_touches = Column(Float)
    mid_3rd_touches = Column(Float)
    att_3rd_touches = Column(Float)
    att_box_touches = Column(Float)
    live_touches = Column(Float)
    att_takeons = Column(Float)
    succ_takeons = Column(Float)
    succ_pct_takeons = Column(Float)
    tkld_takeons = Column(Float)
    tkld_pct_takeons = Column(Float)
    carries = Column(Float)
    tot_dist_carried = Column(Float)
    prg_dist_carried = Column(Float)
    prg_carries = Column(Float)
    carries_into_3rd = Column(Float)
    carries_into_box = Column(Float)
    miscontrols = Column(Float)
    dispossessed = Column(Float)
    passes_rec = Column(Float)
    prg_passes_rec = Column(Float)

    # Shooting
    gf = Column(Float)
    sh = Column(Float)
    sot = Column(Float)
    sot_pct = Column(Float)
    g_per_sh = Column(Float)
    g_per_sot = Column(Float)
    avg_dis_of_sh = Column(Float)
    fk = Column(Float)
    pk = Column(Float)
    pk_att_for = Column(Float)
    xg = Column(Float)
    npxg = Column(Float)
    npxg_per_sh = Column(Float)
    g_minus_xg = Column(Float)
    npg_minus_xg = Column(Float)


    def as_dict(self):
        return {column.name: getattr(self, column.name) for column in self.__table__.columns}
    
    def __repr__(self):
        return f"<RawMatch(date={self.date}, season={self.season}, team={self.team}, opponent={self.opponent})>"